pipeline{
    agent any
    tools{
        maven 'localMaven'
    }
    stages{
        stage('build'){
            steps{
                sh 'mvn -f server/pom.xml clean package'
            }
            post{
                success{
                    ech 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
    }
}